resources:
  limits:
    cpu: "1.0"
    memory: "2048Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
targetAverageUtilization: 100
ingress:
  enabled: true
  tls:
    catalyst-redirect:
      secretName: catalyst.uw.edu-ingress-cert
      hosts:
        - catalyst.uw.edu
        - catalyst.washington.edu
        - catalysttools.washington.edu
    solstice-redirect:
      secretName: solstice.uw.edu-ingress-cert
      hosts:
        - solstice.uw.edu
    catalyst-archive:
      secretName: archive.catalyst.uw.edu-ingress-cert
      hosts:
        - archive.catalyst.uw.edu
  hosts:
    catalyst-redirect:
      host: catalyst.uw.edu
      paths:
        - "/"
    catalystwa-redirect:
      host: catalyst.washington.edu
      paths:
        - "/"
    catalysttools-redirect:
      host: catalysttools.washington.edu
      paths:
        - "/"
    solstice-redirect:
      host: solstice.uw.edu
      paths:
        - "/"
    catalyst-archive:
      host: archive.catalyst.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'archive.catalyst.uw.edu') {
        if ($uri = '/webq/survey/shawkey/357671') {
          return 301 https://docs.google.com/forms/d/e/1FAIpQLScPAvEH3tXUNJBIX7qTNcNrvYl1XXCbrAPuQ599CDEyOdFFvQ/viewform
        }
        return 301 $scheme://itconnect.uw.edu/learn/tools/catalyst-web-tools/retirement/;
      }
lifecycle:
  enabled: true
  preStop:
    enabled: true
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: false
externalService:
  enabled: true
  name: catalyst-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.232
  servicePort: 3306
database:
  engine: mysql
  name: catalyst_utils_prod
  hostname: catalyst-db-service
  secretName: archive.catalyst.uw.edu-sql-secrets
repo: catalyst
instance: prod
memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate
gcsCredentials:
  mounted: true
  secretName: archive.catalyst.uw.edu-gcs-credentials
mountedSecrets:
  enabled: true
  mountPath: /ssl
  secretName: archive.catalyst.uw.edu-openssl-conf
cronjob:
  enabled: true
  jobs:
    - name: update-person-attr
      schedule: "*/20 15-23 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["update_person_attr"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
    - name: update-netid-admins
      schedule: "15 12 * * 1,4"
      command: ["/scripts/management_command.sh"]
      args: ["update_netid_admins"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
certs:
  mounted: true
  certPath: /certs/apps.catalyst.uw.edu-uwca.cert
  keyPath: /certs/apps.catalyst.uw.edu-uwca.key
  secretName: archive.catalyst.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: prod

  - name: PWS_ENV
    value: PROD

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "10"

  - name: CATALYST_ENV
    value: PROD
  - name: CATALYST_TIMEOUT
    value: "300"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://archive.catalyst.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: archive.catalyst.uw.edu

  - name: OPENSSL_CONF
    value: /ssl/openssl.cnf

externalSecrets:
  enabled: true
  secrets:
    - name: archive.catalyst.uw.edu-secrets
      externalKey: catalyst/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: storage-bucket-name
          property: storage-bucket-name
    - name: archive.catalyst.uw.edu-shared-secrets
      externalKey: catalyst/shared/secrets
      data:
        - name: storage-project-id
          property: storage-project-id
    - name: archive.catalyst.uw.edu-sql-secrets
      externalKey: catalyst/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: archive.catalyst.uw.edu-gcs-credentials
      externalKey: catalyst/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: archive.catalyst.uw.edu-uwca-certs
      externalKey: catalyst/prod/uwca-certs
      data:
        - name: apps.catalyst.uw.edu-uwca.cert
          property: apps.catalyst.uw.edu-uwca.cert
        - name: apps.catalyst.uw.edu-uwca.key
          property: apps.catalyst.uw.edu-uwca.key
    - name: archive.catalyst.uw.edu-ic-certs
      externalKey: catalyst/prod/ic-certs
      data:
        - name: archive.catalyst.uw.edu-ic.cert
          property: archive.catalyst.uw.edu-ic.cert
        - name: archive.catalyst.uw.edu-ic.key
          property: archive.catalyst.uw.edu-ic.key
    - name: archive.catalyst.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert
    - name: archive.catalyst.uw.edu-openssl-conf
      externalKey: openssl-conf
      data:
        - name: openssl.cnf
          property: openssl.cnf

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: archive.catalyst.uw.edu-secrets
    secretKey: django-secret
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: archive.catalyst.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: archive.catalyst.uw.edu-shared-secrets
    secretKey: storage-project-id
  samlSPCert:
    name: SP_CERT
    secretName: archive.catalyst.uw.edu-ic-certs
    secretKey: archive.catalyst.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: archive.catalyst.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
