resources:
  limits:
    cpu: "1.0"
    memory: "2048Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
targetAverageUtilization: 100
ingress:
  enabled: true
  tls:
    catalyst:
      secretName: apps.catalyst.uw.edu-ingress-cert
      hosts:
        - apps.catalyst.uw.edu
  hosts:
    catalyst:
      host: apps.catalyst.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
lifecycle:
  enabled: true
  preStop:
    enabled: true
autoscaling:
  enabled: false
replicaCount: 1
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: false
externalService:
  enabled: true
  name: catalyst-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.232
  servicePort: 3306
database:
  engine: mysql
  name: catalyst_utils_prod
  hostname: catalyst-db-service
  secretName: apps.catalyst.uw.edu-sql-secrets
repo: catalyst
instance: prod
image:
  repository: gcr.io/uwit-mci-axdd/catalyst
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate
gcsCredentials:
  mounted: true
  secretName: apps.catalyst.uw.edu-gcs-credentials
cronjob:
  enabled: true
  jobs:
    - name: export-surveys
      schedule: "*/9 * * * *"
      command: ["/scripts/management_command.sh"]
      args: ["export_surveys"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
    - name: export-gradebooks
      schedule: "40 15-23 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["export_gradebooks"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
    - name: update-person-attr
      schedule: "*/20 15-23 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["update_person_attr"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
    - name: update-survey-attr
      schedule: "*/9 * * * *"
      command: ["/scripts/management_command.sh"]
      args: ["update_survey_attr"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
    - name: update-gradebook-attr
      schedule: "*/27 * * * *"
      command: ["/scripts/management_command.sh"]
      args: ["update_gradebook_attr"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
    - name: update-netid-admins
      schedule: "15 12 * * 1,4"
      command: ["/scripts/management_command.sh"]
      args: ["update_netid_admins"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
    - name: update-authz-groups
      schedule: "45 12 * * 3"
      command: ["/scripts/management_command.sh"]
      args: ["update_authz_groups"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
certs:
  mounted: true
  certPath: /certs/apps.catalyst.uw.edu-uwca.cert
  keyPath: /certs/apps.catalyst.uw.edu-uwca.key
  secretName: apps.catalyst.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: prod

  - name: PWS_ENV
    value: PROD

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "10"

  - name: CATALYST_ENV
    value: PROD
  - name: CATALYST_TIMEOUT
    value: "300"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://apps.catalyst.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: apps.catalyst.uw.edu

externalSecrets:
  enabled: true
  secrets:
    - name: apps.catalyst.uw.edu-secrets
      externalKey: axdd/kv/data/catalyst/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: storage-bucket-name
          property: storage-bucket-name
    - name: apps.catalyst.uw.edu-shared-secrets
      externalKey: axdd/kv/data/catalyst/shared/secrets
      data:
        - name: storage-project-id
          property: storage-project-id
    - name: apps.catalyst.uw.edu-sql-secrets
      externalKey: axdd/kv/data/catalyst/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: apps.catalyst.uw.edu-gcs-credentials
      externalKey: axdd/kv/data/catalyst/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: apps.catalyst.uw.edu-uwca-certs
      externalKey: axdd/kv/data/catalyst/prod/uwca-certs
      data:
        - name: apps.catalyst.uw.edu-uwca.cert
          property: apps.catalyst.uw.edu-uwca.cert
        - name: apps.catalyst.uw.edu-uwca.key
          property: apps.catalyst.uw.edu-uwca.key
    - name: apps.catalyst.uw.edu-ic-certs
      externalKey: axdd/kv/data/catalyst/prod/ic-certs
      data:
        - name: apps.catalyst.uw.edu-ic.cert
          property: apps.catalyst.uw.edu-ic.cert
    - name: apps.catalyst.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: apps.catalyst.uw.edu-secrets
    secretKey: django-secret
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: apps.catalyst.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: apps.catalyst.uw.edu-shared-secrets
    secretKey: storage-project-id
  samlSPCert:
    name: SP_CERT
    secretName: apps.catalyst.uw.edu-ic-certs
    secretKey: apps.catalyst.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: apps.catalyst.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
