# Generated by Django 2.2.24 on 2021-11-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAuth',
            fields=[
                ('object_auth_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('netid', models.CharField(max_length=32)),
                ('is_entity', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('is_research_confidential', models.BooleanField(default=False)),
                ('is_research_anonymous', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(null=True)),
                ('unpublish_date', models.DateTimeField(null=True)),
                ('security_type', models.SlugField(null=True)),
                ('object_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalyst_utils.ObjectAuth')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalyst_utils.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('gradebook_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('object_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalyst_utils.ObjectAuth')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalyst_utils.Person')),
            ],
        ),
    ]
