# Generated by Django 2.2.24 on 2021-11-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('gradebook_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('create_date', models.DateTimeField()),
                ('authz_id', models.IntegerField()),
            ],
            options={
                'db_table': 'GradeBook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('login_realm_id', models.IntegerField(default=1)),
                ('login_name', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('last_login_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('object_auth_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAttr',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalyst_utils.Person')),
                ('is_person', models.BooleanField(null=True)),
                ('is_current', models.BooleanField(null=True)),
                ('preferred_name', models.CharField(max_length=255, null=True)),
                ('preferred_surname', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
