# Generated by Django 2.2.24 on 2021-11-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAttr',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalyst_utils.Person')),
                ('is_person', models.BooleanField(null=True)),
                ('is_current', models.BooleanField(null=True)),
                ('preferred_name', models.CharField(max_length=255, null=True)),
                ('preferred_surname', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
