# Generated by Django 2.2.24 on 2021-11-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWrapper',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=255)),
                ('model_package', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'GroupWrapper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleInCrowd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_id', models.IntegerField()),
            ],
            options={
                'db_table': 'PeopleInCrowd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleImplementation',
            fields=[
                ('role_implementation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('object_auth_id', models.IntegerField()),
            ],
            options={
                'db_table': 'RoleImplementation',
                'managed': False,
            },
        ),
    ]
