# Generated by Django 2.2.24 on 2021-11-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0002_groupwrapper_peopleincrowd_roleimplementation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalyst_utils.Person')),
            ],
        ),
        migrations.AddIndex(
            model_name='persongroup',
            index=models.Index(fields=['group_id'], name='group_id_idx'),
        ),
    ]
