# Generated by Django 2.2.24 on 2021-11-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0003_auto_20211122_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='personattr',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
