# Generated by Django 2.2.25 on 2022-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0005_auto_20211215_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattr',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='surveyattr',
            name='last_response',
            field=models.DateTimeField(null=True),
        ),
    ]
