# Copyright 2023 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0


# Generated by Django 2.2.25 on 2021-12-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAttr',
            fields=[
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='catalyst_utils.Survey')),
                ('question_count', models.IntegerField(null=True)),
                ('response_count', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
