# Copyright 2023 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0


# Generated by Django 2.2.25 on 2021-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0002_auto_20211208_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattr',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
