# Copyright 2022 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.25 on 2022-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0005_auto_20211215_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradebook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='groupwrapper',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='peopleincrowd',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roleimplementation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='surveyattr',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='surveyattr',
            name='last_response',
            field=models.DateTimeField(null=True),
        ),
    ]
