# Copyright 2025 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0


# Generated by Django 3.2.13 on 2022-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_utils', '0006_auto_20220112_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattr',
            name='job_id',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='surveyattr',
            index=models.Index(fields=['job_id'], name='s_job_id_idx'),
        ),
    ]
